var heroes = [
  {
    "Name": "Abaddon",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 0,
    "slug": "abaddon"
  },
  {
    "Name": "Alchemist",
    "Durable": 2,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "alchemist"
  },
  {
    "Name": "Ancient Apparition",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "ancient_apparition"
  },
  {
    "Name": "Anti-mage",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 3,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "antimage"
  },
  {
    "Name": "Axe",
    "Durable": 3,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 1,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "7",
    "slug": "axe"
  },
  {
    "Name": "Bane",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 3,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "bane"
  },
  {
    "Name": "Batrider",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 1,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "batrider"
  },
  {
    "Name": "Beastmaster",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "beastmaster"
  },
  {
    "Name": "Bloodseeker",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 1,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "bloodseeker"
  },
  {
    "Name": "Bounty Hunter",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 2,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "bounty_hunter"
  },
  {
    "Name": "Brewmaster",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "7",
    "slug": "brewmaster"
  },
  {
    "Name": "Bristleback",
    "Durable": 3,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "bristleback"
  },
  {
    "Name": "Broodmother",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 3,
    "Lane Support": 0,
    "Total": "5",
    "slug": "broodmother"
  },
  {
    "Name": "Centaur Warrunner",
    "Durable": 3,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "centaur"
  },
  {
    "Name": "Chaos Knight",
    "Durable": 1,
    "Carry": 2,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "6",
    "slug": "chaos_knight"
  },
  {
    "Name": "Chen",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 3,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 3,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "8",
    "slug": "chen"
  },
  {
    "Name": "Clinkz",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 2,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "clinkz"
  },
  {
    "Name": "Clockwerk",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "rattletrap"
  },
  {
    "Name": "Crystal Maiden",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 3,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 1,
    "Total": "8",
    "slug": "crystal_maiden"
  },
  {
    "Name": "Dark Seer",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "dark_seer"
  },
  {
    "Name": "Dazzle",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 3,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 3,
    "Total": "6",
    "slug": "dazzle"
  },
  {
    "Name": "Death Prophet",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "4",
    "slug": "death_prophet"
  },
  {
    "Name": "Disruptor",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 1,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "disruptor"
  },
  {
    "Name": "Doom",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "doom_bringer"
  },
  {
    "Name": "Dragon Knight",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "7",
    "slug": "dragon_knight"
  },
  {
    "Name": "Drow Ranger",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "drow_ranger"
  },
  {
    "Name": "Earthshaker",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 1,
    "Escape": 0,
    "Initiator": 3,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 1,
    "Total": "7",
    "slug": "earthshaker"
  },
  {
    "Name": "Elder Titan",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "elder_titan"
  },
  {
    "Name": "Enchantress",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 0,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 1,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "6",
    "slug": "enchantress"
  },
  {
    "Name": "Enigma",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 2,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "8",
    "slug": "enigma"
  },
  {
    "Name": "Faceless Void",
    "Durable": 0,
    "Carry": 3,
    "Disabler": 1,
    "Support": 0,
    "Escape": 1,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "7",
    "slug": "faceless_void"
  },
  {
    "Name": "Gyrocopter",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "gyrocopter"
  },
  {
    "Name": "Huskar",
    "Durable": 1,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "huskar"
  },
  {
    "Name": "Invoker",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "invoker"
  },
  {
    "Name": "IO",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 3,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 2,
    "Total": "6",
    "slug": "wisp"
  },
  {
    "Name": "Jakiro",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 2,
    "Lane Support": 2,
    "Total": "7",
    "slug": "jakiro"
  },
  {
    "Name": "Juggernaut",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": 3,
    "slug": "juggernaut"
  },
  {
    "Name": "Keeper of the Light",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 2,
    "Total": "6",
    "slug": "keeper_of_the_light"
  },
  {
    "Name": "Kunkka",
    "Durable": 1,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "kunkka"
  },
  {
    "Name": "Leshrac",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 3,
    "Lane Support": 0,
    "Total": "8",
    "slug": "leshrac"
  },
  {
    "Name": "Lich",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 3,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 3,
    "Total": "8",
    "slug": "lich"
  },
  {
    "Name": "Lifestealer",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 1,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "life_stealer"
  },
  {
    "Name": "Lina",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "lina"
  },
  {
    "Name": "Lion",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 3,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 0,
    "Lane Support": 2,
    "Total": "10",
    "slug": "lion"
  },
  {
    "Name": "Lone Druid",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 1,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "7",
    "slug": "lone_druid"
  },
  {
    "Name": "Luna",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "luna"
  },
  {
    "Name": "Lycanthrope",
    "Durable": 1,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 2,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "7",
    "slug": "lycan"
  },
  {
    "Name": "Magnus",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 3,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "magnataur"
  },
  {
    "Name": "Medusa",
    "Durable": 0,
    "Carry": 3,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "medusa"
  },
  {
    "Name": "Meepo",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "meepo"
  },
  {
    "Name": "Mirana",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "mirana"
  },
  {
    "Name": "Morphling",
    "Durable": 0,
    "Carry": 3,
    "Disabler": 0,
    "Support": 0,
    "Escape": 3,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "8",
    "slug": "morphling"
  },
  {
    "Name": "Naga Siren",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 2,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "6",
    "slug": "naga_siren"
  },
  {
    "Name": "Nature's Prophet",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 2,
    "Nuker": 0,
    "Pusher": 2,
    "Lane Support": 0,
    "Total": "6",
    "slug": "furion"
  },
  {
    "Name": "Necrolyte",
    "Durable": 1,
    "Carry": 1,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "necrolyte"
  },
  {
    "Name": "Night Stalker",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "night_stalker"
  },
  {
    "Name": "Nyx Assassin",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "nyx_assassin"
  },
  {
    "Name": "Ogre Magi",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "ogre_magi"
  },
  {
    "Name": "Omniknight",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 1,
    "Total": "4",
    "slug": "omniknight"
  },
  {
    "Name": "Outworld Devourer",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "obsidian_destroyer"
  },
  {
    "Name": "Phantom Assassin",
    "Durable": 0,
    "Carry": 3,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "phantom_assassin"
  },
  {
    "Name": "Phantom Lancer",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 2,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "5",
    "slug": "phantom_lancer"
  },
  {
    "Name": "Puck",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 1,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "puck"
  },
  {
    "Name": "Pudge",
    "Durable": 3,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "pudge"
  },
  {
    "Name": "Pugna",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "4",
    "slug": "pugna"
  },
  {
    "Name": "Queen of Pain",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 3,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "7",
    "slug": "queenofpain"
  },
  {
    "Name": "Razor",
    "Durable": 1,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "razor"
  },
  {
    "Name": "Riki",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "riki"
  },
  {
    "Name": "Rubick",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "rubick"
  },
  {
    "Name": "Sand King",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 3,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "sand_king"
  },
  {
    "Name": "Shadow Demon",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "shadow_demon"
  },
  {
    "Name": "Shadow Fiend",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "nevermore"
  },
  {
    "Name": "Shadow Shaman",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 3,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 3,
    "Lane Support": 0,
    "Total": "8",
    "slug": "shadow_shaman"
  },
  {
    "Name": "Silencer",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "silencer"
  },
  {
    "Name": "Skeleton King",
    "Durable": 3,
    "Carry": 2,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "7",
    "slug": "skeleton_king"
  },
  {
    "Name": "Skywrath Mage",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "skywrath_mage"
  },
  {
    "Name": "Slardar",
    "Durable": 2,
    "Carry": 2,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "slardar"
  },
  {
    "Name": "Slark",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 3,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "slark"
  },
  {
    "Name": "Sniper",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "sniper"
  },
  {
    "Name": "Spectre",
    "Durable": 1,
    "Carry": 3,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "spectre"
  },
  {
    "Name": "Spirit Breaker",
    "Durable": 2,
    "Carry": 1,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "spirit_breaker"
  },
  {
    "Name": "Storm Spirit",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 1,
    "Support": 0,
    "Escape": 2,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "7",
    "slug": "storm_spirit"
  },
  {
    "Name": "Sven",
    "Durable": 0,
    "Carry": 1,
    "Disabler": 2,
    "Support": 1,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "sven"
  },
  {
    "Name": "Templar Assassin",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "templar_assassin"
  },
  {
    "Name": "Tidehunter",
    "Durable": 3,
    "Carry": 0,
    "Disabler": 2,
    "Support": 1,
    "Escape": 0,
    "Initiator": 3,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "9",
    "slug": "tidehunter"
  },
  {
    "Name": "Timbersaw",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "shredder"
  },
  {
    "Name": "TInker",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "4",
    "slug": "tinker"
  },
  {
    "Name": "Tiny",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 2,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "6",
    "slug": "tiny"
  },
  {
    "Name": "Treant Protector",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 2,
    "Total": "7",
    "slug": "treant"
  },
  {
    "Name": "Troll Warlord",
    "Durable": 0,
    "Carry": 3,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "troll_warlord"
  },
  {
    "Name": "Tusk",
    "Durable": 1,
    "Carry": 0,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "tusk"
  },
  {
    "Name": "Undying",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "5",
    "slug": "undying"
  },
  {
    "Name": "Ursa",
    "Durable": 1,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 2,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "ursa"
  },
  {
    "Name": "Vengeful Spirit",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 2,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 1,
    "Total": "5",
    "slug": "vengefulspirit"
  },
  {
    "Name": "Venomancer",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 2,
    "Escape": 0,
    "Initiator": 1,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 1,
    "Lane Support": 0,
    "Total": "5",
    "slug": "venomancer"
  },
  {
    "Name": "Viper",
    "Durable": 1,
    "Carry": 1,
    "Disabler": 0,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 2,
    "slug": "viper"
  },
  {
    "Name": "Visage",
    "Durable": 2,
    "Carry": 0,
    "Disabler": 1,
    "Support": 0,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 2,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "visage"
  },
  {
    "Name": "Warlock",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 2,
    "Escape": 0,
    "Initiator": 2,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 2,
    "Total": "7",
    "slug": "warlock"
  },
  {
    "Name": "Weaver",
    "Durable": 0,
    "Carry": 2,
    "Disabler": 0,
    "Support": 0,
    "Escape": 3,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "5",
    "slug": "weaver"
  },
  {
    "Name": "Windrunner",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 1,
    "Escape": 1,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 1,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "windrunner"
  },
  {
    "Name": "Witch Doctor",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 1,
    "Support": 2,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 0,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": 3,
    "slug": "witch_doctor"
  },
  {
    "Name": "Zeus",
    "Durable": 0,
    "Carry": 0,
    "Disabler": 0,
    "Support": 1,
    "Escape": 0,
    "Initiator": 0,
    "Jungler": 0,
    "Nuker": 3,
    "Pusher": 0,
    "Lane Support": 0,
    "Total": "4",
    "slug": "zuus"
  }
];